// SwiftBar menubar plugin installer for sshshot on macOS.
//
// `sshshot menubar install` writes a shell-script plugin to
// ~/SwiftBarPlugins/ that renders a status icon in the macOS menu bar and
// invokes `sshshot` commands on click — target switching, pause/resume,
// daemon control. SwiftBar (https://swiftbar.app) is the host runtime, a
// free menu-bar app that exec's plugin scripts and renders their stdout
// using a markdown-like syntax (see `renderPlugin` below).
//
// The plugin is a self-contained zsh script with three responsibilities:
//   1. Read sshshot state (status --json + config.json fallback) and emit a
//      menu hierarchy with click-actions wired to this same script.
//   2. When invoked with `param1=<action>`, dispatch the corresponding
//      `sshshot` subcommand and surface a notification.
//   3. Refresh every 5 s (cheap — single `status --json` + jq calls).
//
// Why a script rather than a SwiftBar app proper? SwiftBar exec's the
// shebang and pipes stdout. No compilation, no signing, no Xcode. Edits
// take effect on the next 5 s tick. Trivial to distribute via this CLI.
//
// macOS-only. install/uninstall/status are no-ops on other platforms,
// with a clear message.

import { spawnSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'

// Escape an arbitrary string so it can be embedded as a single-quoted zsh
// literal. Required for any value that ends up inside the generated plugin
// script — process.env.PATH, process.argv[1], etc. — so an exotic character
// in the source can't break parsing or trigger command substitution. zsh
// single-quote semantics: nothing inside '…' is interpreted, but ' itself
// must be escaped by closing the quote, inserting an escaped ', and
// reopening: foo'bar → 'foo'\''bar'.
export function shellSingleQuote(s: string): string {
  return "'" + s.replace(/'/g, "'\\''") + "'"
}

export const MENUBAR_PLUGIN_FILENAME = 'sshshot.5s.sh'

export interface MenubarPaths {
  pluginDir: string
  pluginFile: string
}

export function getMenubarPaths(): MenubarPaths {
  const pluginDir = path.join(os.homedir(), 'SwiftBarPlugins')
  return {
    pluginDir,
    pluginFile: path.join(pluginDir, MENUBAR_PLUGIN_FILENAME)
  }
}

// The plugin script content. Embedded as a template literal so the CLI is
// a single distributable file and users don't need to download anything
// separately. The script is parameter-substituted with:
//   - `sshshotBin`: the sshshot script (with #!/usr/bin/env node shebang)
//   - `pathPrefix`: the install-time PATH (process.env.PATH), captured so
//                   the plugin and any subprocess (the daemon!) can find
//                   node, pngpaste (for clipboard reads), pbcopy, ssh, jq,
//                   and any other tools the user has on their shell PATH.
//                   SwiftBar runs plugins with a minimal /usr/bin:/bin —
//                   without this prefix, the daemon's `which pngpaste`
//                   silently fails, clipboard screenshots get dropped, and
//                   only file-saved screenshots are caught.
export function renderPlugin(opts: { sshshotBin: string; pathPrefix: string }): string {
  return `#!/bin/zsh
# <swiftbar.title>sshshot</swiftbar.title>
# <swiftbar.version>v1.0</swiftbar.version>
# <swiftbar.author>flamerged</swiftbar.author>
# <swiftbar.desc>Switch / pause / inspect sshshot daemon and its targets</swiftbar.desc>
# <swiftbar.refresh>5s</swiftbar.refresh>
#
# Generated by 'sshshot menubar install'. Edit by hand if you want — the
# install command will overwrite this file though. To customize permanently,
# fork the script template in src/menubar.ts.

set -u
# SwiftBar invokes plugins with a minimal PATH (/usr/bin:/bin) that's missing
# node (nvm/homebrew), pngpaste (clipboard reads), and other tools the user's
# shell normally has. We capture the install-time PATH and prepend it so
# both the plugin and any daemon it spawns can find everything. Re-run
# 'sshshot menubar install' from your usual shell to refresh this if you
# install new tools or change your PATH.
#
# Values are single-quote escaped at render-time (see shellSingleQuote in
# src/menubar.ts) so paths containing quotes / $ / backticks can't break
# parsing or trigger command substitution.
export PATH=${shellSingleQuote(opts.pathPrefix)}":\${PATH:-/usr/bin:/bin}"
SSHSHOT=${shellSingleQuote(opts.sshshotBin)}
CONFIG_PATH="\${HOME}/.config/sshshot/config.json"
LOG_DIR="\${HOME}/.config/sshshot/logs"

# --- Click-action handlers (run before any output) ---
ACTION="\${1:-}"
case "$ACTION" in
  target)
    NAME="\${2:-}"
    [[ -z "$NAME" ]] && exit 1
    "$SSHSHOT" target "$NAME" >/dev/null 2>&1
    osascript -e "display notification \\"Active target → $NAME\\" with title \\"sshshot\\""
    exit 0
    ;;
  pause)
    "$SSHSHOT" pause >/dev/null 2>&1
    osascript -e "display notification \\"Paused\\" with title \\"sshshot\\""
    exit 0
    ;;
  resume)
    "$SSHSHOT" resume >/dev/null 2>&1
    osascript -e "display notification \\"Resumed\\" with title \\"sshshot\\""
    exit 0
    ;;
  start)
    # sshshot start prompts for target interactively when none is given —
    # SwiftBar can't answer prompts, so we pass the saved activeTarget
    # explicitly. Falls back to 'local' if nothing is configured yet.
    TGT=$(jq -r '.activeTarget // "local"' "$CONFIG_PATH" 2>/dev/null)
    [[ -z "$TGT" || "$TGT" == "null" ]] && TGT="local"
    "$SSHSHOT" start "$TGT" >/dev/null 2>&1
    osascript -e "display notification \\"Daemon started ($TGT)\\" with title \\"sshshot\\""
    exit 0
    ;;
  stop)
    "$SSHSHOT" stop >/dev/null 2>&1
    osascript -e "display notification \\"Daemon stopped\\" with title \\"sshshot\\""
    exit 0
    ;;
  restart)
    TGT=$(jq -r '.activeTarget // "local"' "$CONFIG_PATH" 2>/dev/null)
    [[ -z "$TGT" || "$TGT" == "null" ]] && TGT="local"
    "$SSHSHOT" stop >/dev/null 2>&1
    sleep 2
    "$SSHSHOT" start "$TGT" >/dev/null 2>&1
    osascript -e "display notification \\"Daemon restarted ($TGT)\\" with title \\"sshshot\\""
    exit 0
    ;;
  open-config)
    open "$CONFIG_PATH"
    exit 0
    ;;
  open-log)
    LATEST=$(ls -t "\${LOG_DIR}"/daemon.log* 2>/dev/null | head -1)
    [[ -n "$LATEST" ]] && open "$LATEST" || osascript -e 'display notification "No log file yet" with title "sshshot"'
    exit 0
    ;;
esac

# --- Read current state ---
STATUS_JSON="$("$SSHSHOT" status --json 2>/dev/null | sed -n '/^{/,$p')"
if [[ -z "$STATUS_JSON" ]]; then
  RUNNING="false"; PID=""; ACTIVE=""; PAUSED="false"
else
  RUNNING=$(echo "$STATUS_JSON" | jq -r '.running // false' 2>/dev/null)
  PID=$(echo "$STATUS_JSON"      | jq -r '.pid // ""' 2>/dev/null)
  ACTIVE=$(echo "$STATUS_JSON"   | jq -r '.activeTarget // ""' 2>/dev/null)
  PAUSED=$(echo "$STATUS_JSON"   | jq -r '.paused // false' 2>/dev/null)
fi

# Fallback for older status output: read config directly
if [[ -z "$ACTIVE" ]] && [[ -f "$CONFIG_PATH" ]]; then
  ACTIVE=$(jq -r '.activeTarget // ""' "$CONFIG_PATH" 2>/dev/null)
fi
[[ -z "$ACTIVE" ]] && ACTIVE="<unset>"

# Active short label for menu bar header (strip user@, drop -ts suffix)
ACTIVE_SHORT="\${ACTIVE#*@}"
ACTIVE_SHORT="\${ACTIVE_SHORT%-ts}"

# Pull remotes list
REMOTES=()
if [[ -f "$CONFIG_PATH" ]]; then
  while IFS= read -r r; do REMOTES+=("$r"); done < <(jq -r '.remotes[]' "$CONFIG_PATH" 2>/dev/null)
fi

# --- Header (visible in menu bar) ---
if [[ "$RUNNING" == "true" ]]; then
  if [[ "$PAUSED" == "true" ]]; then
    echo ":camera.fill: :pause.fill: \${ACTIVE_SHORT} | color=#ff9800"
  else
    echo ":camera.fill: \${ACTIVE_SHORT}"
  fi
else
  echo ":camera.fill: idle | color=gray"
fi
echo "---"

# --- Status block ---
echo "📸 sshshot"
if [[ "$RUNNING" == "true" ]]; then
  echo "--Daemon: running (PID \${PID}) | color=#4caf50 size=12"
else
  echo "--Daemon: not running | color=#9e9e9e size=12"
fi
echo "--Active target: \${ACTIVE} | size=12 font=Menlo"
if [[ "$PAUSED" == "true" ]]; then
  echo "--Paused: yes | color=#ff9800 size=12"
else
  echo "--Paused: no | size=12"
fi
echo "---"

# --- Daemon control ---
if [[ "$RUNNING" == "true" ]]; then
  if [[ "$PAUSED" == "true" ]]; then
    echo "▶ Resume | bash=$0 param1=resume terminal=false refresh=true"
  else
    echo "⏸ Pause | bash=$0 param1=pause terminal=false refresh=true"
  fi
  echo "🔄 Restart daemon | bash=$0 param1=restart terminal=false refresh=true"
  echo "⏹ Stop daemon | bash=$0 param1=stop terminal=false refresh=true"
else
  echo "▶ Start daemon | bash=$0 param1=start terminal=false refresh=true"
fi
echo "---"

# --- Target switcher ---
echo "🎯 Switch target"
for r in "\${REMOTES[@]}"; do
  if [[ "$r" == "$ACTIVE" ]]; then
    echo "--✓ \${r} (active) | color=#4caf50 size=12 font=Menlo"
  else
    echo "--▶ \${r} | bash=$0 param1=target param2=\${r} terminal=false refresh=true size=12 font=Menlo"
  fi
done
echo "---"

# --- Utility ---
echo "📂 Open config | bash=$0 param1=open-config terminal=false"
echo "📜 Open latest log | bash=$0 param1=open-log terminal=false"
echo "🔄 Refresh | refresh=true"
`
}

function isMacOS(): boolean {
  return process.platform === 'darwin'
}

export interface InstallResult {
  installed: boolean
  pluginFile: string
  swiftbarPresent: boolean
  message: string
}

// Resolve the sshshot binary path the plugin should invoke. Prefer
// `process.argv[1]` — that's the running script with its shebang.
function resolveBinaryInvocation(): string {
  // When installed via npm (`npm i -g`), process.argv[1] is the bin shim,
  // which is what we want — it correctly handles future PATH changes.
  const bin = process.argv[1]
  if (bin && fs.existsSync(bin)) {
    return bin
  }
  // Fallback: assume `sshshot` is on PATH.
  return 'sshshot'
}

// Capture the install-time PATH so the plugin (and any daemon it spawns)
// can find node, pngpaste, pbcopy, ssh, jq, and the rest of the user's
// shell environment. Falls back to a sensible default that at least
// includes node's directory if process.env.PATH is somehow empty.
function resolvePathPrefix(): string {
  const userPath = process.env.PATH
  if (userPath && userPath.length > 0) {
    return userPath
  }
  return path.dirname(process.execPath)
}

function hasJq(): boolean {
  // The embedded plugin script uses jq to parse `sshshot status --json` and
  // walk the config file. macOS does not ship jq, so install needs to
  // surface this clearly rather than letting the plugin silently render
  // wrong data (every jq call returns empty → daemon shows as not running
  // even when it is).
  const r = spawnSync('jq', ['--version'], { timeout: 3000 })
  return r.status === 0
}

export function install(): InstallResult {
  if (!isMacOS()) {
    return {
      installed: false,
      pluginFile: '',
      swiftbarPresent: false,
      message: 'menubar install is macOS-only (SwiftBar is a macOS app).'
    }
  }

  if (!hasJq()) {
    return {
      installed: false,
      pluginFile: '',
      swiftbarPresent: fs.existsSync('/Applications/SwiftBar.app'),
      message:
        "jq is required by the menu-bar plugin (used to parse sshshot status --json and the config file). Install it first:\n  brew install jq\nThen re-run 'sshshot menubar install'."
    }
  }

  const { pluginDir, pluginFile } = getMenubarPaths()
  fs.mkdirSync(pluginDir, { recursive: true })

  const sshshotBin = resolveBinaryInvocation()
  const pathPrefix = resolvePathPrefix()
  const content = renderPlugin({ sshshotBin, pathPrefix })

  // Atomic write: tmp then rename, so a crash mid-write can't leave a
  // half-rendered plugin that SwiftBar would then exec.
  const tmp = `${pluginFile}.tmp.${process.pid}`
  fs.writeFileSync(tmp, content, { mode: 0o755 })
  fs.renameSync(tmp, pluginFile)
  fs.chmodSync(pluginFile, 0o755)

  const swiftbarPresent = fs.existsSync('/Applications/SwiftBar.app')

  return {
    installed: true,
    pluginFile,
    swiftbarPresent,
    message: swiftbarPresent
      ? `Plugin installed at ${pluginFile}. Open SwiftBar (or it'll pick up on next refresh).`
      : `Plugin installed at ${pluginFile}. SwiftBar not detected — install it with:\n  brew install --cask swiftbar\nThen launch SwiftBar and point its plugin folder at: ${pluginDir}`
  }
}

export interface UninstallResult {
  removed: boolean
  pluginFile: string
  message: string
}

export function uninstall(): UninstallResult {
  if (!isMacOS()) {
    return {
      removed: false,
      pluginFile: '',
      message: 'menubar uninstall is macOS-only.'
    }
  }

  const { pluginFile } = getMenubarPaths()
  if (!fs.existsSync(pluginFile)) {
    return {
      removed: false,
      pluginFile,
      message: `Nothing to remove — no plugin at ${pluginFile}.`
    }
  }
  fs.unlinkSync(pluginFile)
  return {
    removed: true,
    pluginFile,
    message: `Removed plugin at ${pluginFile}.`
  }
}

export interface StatusResult {
  installed: boolean
  pluginFile: string
  swiftbarPresent: boolean
  jqPresent: boolean
}

export function status(): StatusResult {
  const { pluginFile } = getMenubarPaths()
  return {
    installed: fs.existsSync(pluginFile),
    pluginFile,
    swiftbarPresent: isMacOS() && fs.existsSync('/Applications/SwiftBar.app'),
    jqPresent: hasJq()
  }
}

// CLI entry point — called from src/index.ts when the user runs
// `sshshot menubar <subcommand>`.
export function runMenubarCommand(subcommand: string | undefined): void {
  switch (subcommand) {
    case 'install': {
      const r = install()
      console.log(r.message)
      if (!r.installed) {
        process.exit(1)
      }
      return
    }
    case 'uninstall': {
      const r = uninstall()
      console.log(r.message)
      return
    }
    case 'status':
    case undefined: {
      const s = status()
      console.log(`Plugin installed: ${s.installed ? 'yes' : 'no'}`)
      console.log(`Plugin path:      ${s.pluginFile}`)
      console.log(`SwiftBar present: ${s.swiftbarPresent ? 'yes' : 'no'}`)
      console.log(`jq present:       ${s.jqPresent ? 'yes' : 'no (brew install jq)'}`)
      if (!s.installed) {
        console.log("\nInstall with: 'sshshot menubar install'")
      }
      return
    }
    default:
      console.log(`Unknown menubar subcommand: ${subcommand}`)
      console.log('Use one of: install, uninstall, status')
      process.exit(1)
  }
}
